version: '3.8'

services:
  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: esp32-monitor-backend
    restart: unless-stopped
    ports:
      - "3000:8080"  
    environment:
      - NODE_ENV=development
      - PORT=8080 
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/esp32_monitor}
      - CORS_ORIGIN=http://localhost
    volumes:
      - backend_logs:/app/logs
    networks:
      - esp32-network
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: esp32-monitor-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000 
    networks:
      - esp32-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB
  mongodb:
    image: mongo:7.0-alpine
    container_name: esp32-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password123}
      - MONGO_INITDB_DATABASE=esp32_monitor
    volumes:
      - mongodb_data:/data/db
    networks:
      - esp32-network
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: esp32-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD:-password123}
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    networks:
      - esp32-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
  backend_logs:
    driver: local

networks:
  esp32-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16